ucell_testproject/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

ucell_testproject/ucell_testproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ucell_testproject/mainapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Цена')
    color = models.CharField(max_length=200, verbose_name='Цвет')
    quantity = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

ucell_testproject/mainapp/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import logout as logout_view
from django.contrib.auth import login as login_view
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from .models import Product


def index(request):
    if request.method == 'GET':
        if 'search' in request.GET:
            products = Product.objects.filter(name__contains=request.GET['search'])
        else:
            products = Product.objects.all()
        if request.user.is_authenticated:
            template = 'mainapp/index.html'
            context = {
                'products': products
            }
            return render(request, template, context)
        else:
            return redirect('mainapp:login', permanent=True)
    elif request.method == 'POST':
        product = Product.objects.get(id=request.POST['id'])
        product.quantity = request.POST['quantity']
        product.save()
        return redirect('mainapp:index', permanent=True)
    else:
        return HttpResponseForbidden()


def login(request):
    if request.method == 'GET':
        template = 'mainapp/login.html'
        if 'auth' in request.GET:
            context = {'wrong_auth': request.GET['auth']}
            return render(request, template, context)
        else:
            return render(request, template)
    elif request.method == 'POST':
        try:
            User.objects.get(username=request.POST['username'])
        except ObjectDoesNotExist:
            return redirect('/login/?auth=wrong_login', permanent=True, )
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login_view(request, user)
            return redirect('mainapp:index', permanent=True)
        else:
            return redirect('/login/?auth=wrong_password', permanent=True,)
    else:
        return HttpResponseForbidden()
    pass


def logout(request):
    logout_view(request)
    return redirect('mainapp:login')

ucell_testproject/mainapp/templates/mainapp/index.html
{% extends 'wrapper.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
    <div class="container-fluid content invisible">
        <header>
            <div class="row pt-3">
                <div class="col-12 col-lg-2">
                    <div class="header-block"></div>
                </div>
                <div class="col-12 col-lg-8">
                    <div class="title header-block">
                        <h1>Список товаров</h1>
                    </div>
                </div>
                <div class="col-12 col-lg-2 text-center">
                    <div class="logout header-block">
                        <a href="{% url 'mainapp:logout' %}" class="btn btn-danger">Выйти</a>
                    </div>
                </div>
            </div>
        </header>
        <div class="row">
            <div class="col-12">
                <div class="search header-block">
                    <form action="" method="GET" class="search__form">
                        <input type="text" name="search" class="form-control w-75" placeholder="Поиск...">
                        <input type="submit" class="btn btn-success" value="Найти">
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="product-list">
                    <table class="table">
                        <col style="width: 10%">
                        <col style="width: 20%">
                        <col style="width: 10%">
                        <col style="width: 20%">
                        <col style="width: 10%">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Название</th>
                                <th>Цена</th>
                                <th>Цвет</th>
                                <th>Кол-во</th>
                                <th>Изменить кол-во</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if products.count > 0 %}
                                {% for product in products %}
                                    <tr>
                                        <td>{{ product.id }}</td>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.color }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>
                                            <form action="" method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="id" value="{{ product.id }}">
                                                <input type="number" name="quantity" class="form-control w-50 d-inline-block">
                                                <input type="submit" class="btn btn-primary d-inline-block product-list__button" value="Ок">
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="6" style="text-align: center">Нет данных</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <footer></footer>
{% endblock %}

ucell_testproject/mainapp/templates/mainapp/login.html
{% extends 'wrapper.html' %}
{% block title %}Вход{% endblock %}
{% block content %}
    <div class="container-fluid invisible content">
        <div class="row">
            <div class="col-12 auth__background">
                <div class="auth">
                    <h3>Авторизация</h3>
                    <form action="{% url 'mainapp:login' %}" method="POST">
                        {% csrf_token %}
                        <input type="text" name="username" class="form-control mb-3">
                        <input type="password" name="password" class="form-control mb-3">
                        <div class="text-center">
                            <input type="submit" class="btn btn-success" value="Войти">
                        </div>
                        {% if wrong_auth == 'wrong_login' %}
                            <p class="text-danger text-center mt-1">Неправильный логин!</p>
                        {% elif wrong_auth == 'wrong_password' %}
                            <p class="text-danger text-center mt-1">Неправильный пароль!</p>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ucell_testproject/mainapp/templates/wrapper.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}NO TITLE!{% endblock %}</title>
</head>
<body>
{% block content %}
    <h1>NO CONTENT!</h1>
{% endblock %}
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>